### ISSUE TITLE
BUG：在AUBOPE虚拟机中无法正确透传

### ISSUE THREAD

**Issue by Biscuitkids** [AuboRobot/aubo_ros_driver#3]
ROS ：VmWare + Ubuntu 18.04.1 \
AUBOPE ：VmWare + Ubuntu 14.04.1 
\
问题描述： \
执行透传时无法将Moveit规划完成的点位透传到AUBOPE端。
解决方案：\
将 aubo_driver.cpp 中，获取mac缓冲器有效数据长度修改为仅在真实机械臂下获取。

**Comment by dashuaip** [comment]
作者说这是他们最新示教器的ARCS系统使用的aubo_driver，aubope好像用不了

**Comment by oPiZiL** [comment]
AUBOPE请使用 https://github.com/AuboRobot/aubo_robot
